sudo: required
language: generic
servicess: 
  - docker

before_install:
  - docker build -t javkhlanb/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true javkhlanb/docker-react npm run test

